source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'pikapika' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pikapika

  target 'pikapikaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pikapikaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftHTTP', '~> 1.0.4'
pod 'ObjectMapper', '~> 1.3'

end
